POST   http://localhost:8000/api/v1/member/create
Content-Type: application/json

{
     "nom":"FIDIMAHEFA" ,
    "prenom":"Miharintsoa",
     "user_github":"mihary821",
     "fonction":"devellopeur" ,
     "pdc":"lien",
     "mail":"gmail" ,
     "admin":"false"

}

